addSbtPlugin("com.github.gseitz"  % "sbt-release"              % "1.0.13")
addSbtPlugin("com.jsuereth"       % "sbt-pgp"                  % "1.1.2")
addSbtPlugin("com.typesafe.sbt"   % "sbt-git"                  % "1.0.0")
addSbtPlugin("org.portable-scala" % "sbt-scalajs-crossproject" % "1.0.0")
addSbtPlugin("org.scala-js"       % "sbt-scalajs"              % "0.6.33")
addSbtPlugin("org.scalameta"      % "sbt-mdoc"                 % "2.1.5")
addSbtPlugin("pl.project13.scala" % "sbt-jmh"                  % "0.3.7")
