name: CI

on:
  pull_request:
  push:

jobs:
  ci:
    runs-on: ubuntu-latest

    name: Scala v${{ matrix.scala }} / Graal v${{ matrix.graal }} / Java v${{ matrix.java }}
    strategy:
      matrix:
        include:

          - graal: 21.3.2.1
            java: 11
            scala: 2

          - graal: 21.3.2.1
            java: 11
            scala: 3

    steps:
      - name: Git checkout
        uses: actions/checkout@v2


      - name: Setup Scala
        uses: japgolly/setup-everything-scala@v2.0
        with:
          java-version: graalvm-ce-java${{ matrix.java }}@${{ matrix.graal }}

      - name: Build and test
        shell: bash
        run: sbt++field scala${{ matrix.scala }} -DCI=1 clean test
