name: CI

on:
  pull_request:
  push:

jobs:
  ci:
    runs-on: ubuntu-latest

    name: Scala v${{ matrix.scala }} / Graal v${{ matrix.graal }} / Java v${{ matrix.java }}
    strategy:
      matrix:
        include:

          - graal: 21.3.0
            java: 11
            scala: 2.13.6

          - graal: 21.3.0
            java: 11
            scala: 3.0.1

    steps:
      - name: Git checkout
        uses: actions/checkout@v2

      - name: Setup Java and Scala
        uses: olafurpg/setup-scala@v12
        with:
          java-version: graalvm-ce-java${{ matrix.java }}@${{ matrix.graal }}

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Setup Scala.JS
        uses: japgolly/setup-scalajs@v1

      - name: Cache sbt
        uses: coursier/cache-action@v6

      - name: Build and test
        shell: bash
        run: sbt -DCI=1 ++${{ matrix.scala }} clean test
